### ISSUE TITLE
Lazy render preview cards

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#202]
The single most used element on the site is the preview card. We should lazy render it to optimize our rendering. `content-visibility` should help us do this without too much effort:

```css
.preview-card {
  content-visibility: auto;
  contain-intrinsic-size: 144px;
}
```

The `144px` is not exact and should roughly correspond to a card with 2 lines of description, but it will avoid any issues and help the page look normal. This number might take screen size into account, in order to better handle mobile devices etc.
